export default {
    ATUALIZA_VISOR: 'ATUALIZA_VISOR',
    GUARDA_VALOR:'GUARDA_VALOR',
    LIMPA_VISOR:'LIMPA_VISOR',
    LIMPA_VISOR_NA_PROXIMA_OPERACAO:'LIMPA_VISOR_NA_PROXIMA_OPERACAO',
    SETA_OPERACAO:'SETA_OPERACAO',
    LIMPA_OPERACAO:'LIMPA_OPERACAO',
    ENTRAR_COM_DIGITOS_DECIMAIS:'ENTRAR_COM_DIGITOS_DECIMAIS'
}
